### ISSUE TITLE
Suggestion: use systemd instead of supervisorctl for Hawthorne execution

### ISSUE THREAD

**Issue by diamondburned** [indietyp/hawthorne#1]
Hello. I'm suffering greatly from `supervisorctl` and it take quite a while to get it to work (actually haven't yet),

     sudo supervisorctl start hawthorne
     unix:///var/run/supervisor.sock refused connection

I suggest switching to `systemd` service files under `/etc/systemd/system/hawthorne.service`, as the currently supported distros: Debian, Ubuntu and CentOS all support `systemd` service files. OS that does not use `systemd` aren't officially supported by LGSM anyway.

**Comment by indietyp** [comment]
might add support in the future.
